// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter-object.proto

package Foo_Contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SecretSignal         string   `protobuf:"bytes,2,opt,name=secretSignal,proto3" json:"secretSignal,omitempty"`
	Gifts                []*Gift  `protobuf:"bytes,3,rep,name=gifts,proto3" json:"gifts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_872fbb471309833b, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetSecretSignal() string {
	if m != nil {
		return m.SecretSignal
	}
	return ""
}

func (m *HelloRequest) GetGifts() []*Gift {
	if m != nil {
		return m.Gifts
	}
	return nil
}

// The response message containing the greetings
type HelloReply struct {
	Request              *HelloRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_872fbb471309833b, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetRequest() *HelloRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *HelloReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Gift struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gift) Reset()         { *m = Gift{} }
func (m *Gift) String() string { return proto.CompactTextString(m) }
func (*Gift) ProtoMessage()    {}
func (*Gift) Descriptor() ([]byte, []int) {
	return fileDescriptor_872fbb471309833b, []int{2}
}

func (m *Gift) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gift.Unmarshal(m, b)
}
func (m *Gift) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gift.Marshal(b, m, deterministic)
}
func (m *Gift) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gift.Merge(m, src)
}
func (m *Gift) XXX_Size() int {
	return xxx_messageInfo_Gift.Size(m)
}
func (m *Gift) XXX_DiscardUnknown() {
	xxx_messageInfo_Gift.DiscardUnknown(m)
}

var xxx_messageInfo_Gift proto.InternalMessageInfo

func (m *Gift) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "Foo.Contracts.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "Foo.Contracts.HelloReply")
	proto.RegisterType((*Gift)(nil), "Foo.Contracts.Gift")
}

func init() { proto.RegisterFile("greeter-object.proto", fileDescriptor_872fbb471309833b) }

var fileDescriptor_872fbb471309833b = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xa4, 0x50, 0x71, 0x2d, 0x42, 0x32, 0x0c, 0x16, 0x5d, 0xaa, 0x4c, 0x65, 0xc0,
	0x43, 0x11, 0x3c, 0x40, 0x91, 0xa0, 0x03, 0x43, 0x15, 0x86, 0xce, 0x6e, 0xb8, 0x9a, 0x20, 0x27,
	0x97, 0xd8, 0x87, 0x80, 0xd7, 0xe1, 0x49, 0x91, 0x5d, 0x8a, 0x5a, 0xd4, 0xed, 0x7c, 0xfe, 0xad,
	0xef, 0xf3, 0x0f, 0x17, 0xc6, 0x21, 0x32, 0xba, 0x6b, 0x5a, 0xbd, 0x61, 0xc9, 0xaa, 0x75, 0xc4,
	0x24, 0x4e, 0x1f, 0x88, 0xd4, 0x3d, 0x35, 0xec, 0x74, 0xc9, 0x3e, 0xef, 0x60, 0x38, 0x47, 0x6b,
	0xa9, 0xc0, 0xee, 0x1d, 0x3d, 0x0b, 0x01, 0xbd, 0x46, 0xd7, 0x28, 0x93, 0x71, 0x32, 0x39, 0x29,
	0xe2, 0x2c, 0x72, 0x18, 0x7a, 0x2c, 0x1d, 0xf2, 0x73, 0x65, 0x1a, 0x6d, 0x65, 0x1a, 0xef, 0xf6,
	0x76, 0xe2, 0x0a, 0x8e, 0x4c, 0xb5, 0x66, 0x2f, 0xb3, 0x71, 0x36, 0x19, 0x4c, 0xcf, 0xd5, 0x1e,
	0x46, 0x3d, 0x56, 0x6b, 0x2e, 0x36, 0x89, 0xbc, 0x03, 0xf8, 0x45, 0xb6, 0xf6, 0x4b, 0xdc, 0x42,
	0xdf, 0x6d, 0xd8, 0x91, 0x39, 0x98, 0x8e, 0xfe, 0x3d, 0xdd, 0xd5, 0x2b, 0xb6, 0xd9, 0x3f, 0xcf,
	0x74, 0xc7, 0x53, 0x42, 0xbf, 0x46, 0xef, 0xb5, 0x41, 0x99, 0xc5, 0xf5, 0xf6, 0x98, 0x5f, 0x42,
	0x2f, 0x18, 0x1c, 0xfa, 0xdd, 0xec, 0x0e, 0x46, 0x15, 0x29, 0xe3, 0xda, 0x52, 0xe1, 0xa7, 0xae,
	0x5b, 0x8b, 0x5e, 0xbd, 0x06, 0xe6, 0x07, 0x39, 0xfb, 0x32, 0x3b, 0x8b, 0xfc, 0x65, 0x98, 0x17,
	0xa1, 0xc0, 0x45, 0xf2, 0x9d, 0x66, 0xf3, 0xa7, 0xe5, 0xea, 0x38, 0xf6, 0x79, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x56, 0x0e, 0x33, 0x10, 0x67, 0x01, 0x00, 0x00,
}
